// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tagger.proto

package tagger;

public final class Tagger {
  private Tagger() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(tagger.Tagger.tags);
    registry.add(tagger.Tagger.oneofTags);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int TAGS_FIELD_NUMBER = 847939;
  /**
   * <pre>
   * Multiple Tags can be spcified.
   * </pre>
   *
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> tags = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int ONEOF_TAGS_FIELD_NUMBER = 847939;
  /**
   * <pre>
   * Multiple Tags can be spcified.
   * </pre>
   *
   * <code>extend .google.protobuf.OneofOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.OneofOptions,
      java.lang.String> oneofTags = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014tagger.proto\022\006tagger\032 google/protobuf/" +
      "descriptor.proto:-\n\004tags\022\035.google.protob" +
      "uf.FieldOptions\030\303\3403 \001(\t:3\n\noneof_tags\022\035." +
      "google.protobuf.OneofOptions\030\303\3403 \001(\tB.Z," +
      "github.com/davidae/proto-definition/prot" +
      "o/gob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    tags.internalInit(descriptor.getExtensions().get(0));
    oneofTags.internalInit(descriptor.getExtensions().get(1));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
