// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package event;

public final class Event {
  private Event() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GreetingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:event.Greeting)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string from = 1 [(.tagger.tags) = "parquet:&#92;"name=from, type=BYTE_ARRAY, encoding=PLAIN_DICTIONARY&#92;""];</code>
     * @return The from.
     */
    java.lang.String getFrom();
    /**
     * <code>string from = 1 [(.tagger.tags) = "parquet:&#92;"name=from, type=BYTE_ARRAY, encoding=PLAIN_DICTIONARY&#92;""];</code>
     * @return The bytes for from.
     */
    com.google.protobuf.ByteString
        getFromBytes();

    /**
     * <code>.google.protobuf.Timestamp last_updated = 2 [(.tagger.tags) = "parquet:&#92;"name=last_updated, type=INT64, convertedtype=TIMESTAMP_MILLIS&#92;""];</code>
     * @return Whether the lastUpdated field is set.
     */
    boolean hasLastUpdated();
    /**
     * <code>.google.protobuf.Timestamp last_updated = 2 [(.tagger.tags) = "parquet:&#92;"name=last_updated, type=INT64, convertedtype=TIMESTAMP_MILLIS&#92;""];</code>
     * @return The lastUpdated.
     */
    com.google.protobuf.Timestamp getLastUpdated();
    /**
     * <code>.google.protobuf.Timestamp last_updated = 2 [(.tagger.tags) = "parquet:&#92;"name=last_updated, type=INT64, convertedtype=TIMESTAMP_MILLIS&#92;""];</code>
     */
    com.google.protobuf.TimestampOrBuilder getLastUpdatedOrBuilder();

    /**
     * <code>optional string to = 3 [(.tagger.tags) = "parquet:&#92;"name=to, type=BYTE_ARRAY, encoding=PLAIN_DICTIONARY&#92;""];</code>
     * @return Whether the to field is set.
     */
    boolean hasTo();
    /**
     * <code>optional string to = 3 [(.tagger.tags) = "parquet:&#92;"name=to, type=BYTE_ARRAY, encoding=PLAIN_DICTIONARY&#92;""];</code>
     * @return The to.
     */
    java.lang.String getTo();
    /**
     * <code>optional string to = 3 [(.tagger.tags) = "parquet:&#92;"name=to, type=BYTE_ARRAY, encoding=PLAIN_DICTIONARY&#92;""];</code>
     * @return The bytes for to.
     */
    com.google.protobuf.ByteString
        getToBytes();

    /**
     * <code>repeated sint32 publisher_categories = 4 [(.tagger.tags) = "parquet:&#92;"name=publisher_categories, type=INT32 repetitiontype=REPEATED&#92;""];</code>
     * @return A list containing the publisherCategories.
     */
    java.util.List<java.lang.Integer> getPublisherCategoriesList();
    /**
     * <code>repeated sint32 publisher_categories = 4 [(.tagger.tags) = "parquet:&#92;"name=publisher_categories, type=INT32 repetitiontype=REPEATED&#92;""];</code>
     * @return The count of publisherCategories.
     */
    int getPublisherCategoriesCount();
    /**
     * <code>repeated sint32 publisher_categories = 4 [(.tagger.tags) = "parquet:&#92;"name=publisher_categories, type=INT32 repetitiontype=REPEATED&#92;""];</code>
     * @param index The index of the element to return.
     * @return The publisherCategories at the given index.
     */
    int getPublisherCategories(int index);
  }
  /**
   * Protobuf type {@code event.Greeting}
   */
  public static final class Greeting extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:event.Greeting)
      GreetingOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Greeting.newBuilder() to construct.
    private Greeting(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Greeting() {
      from_ = "";
      to_ = "";
      publisherCategories_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Greeting();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Greeting(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              from_ = s;
              break;
            }
            case 18: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (lastUpdated_ != null) {
                subBuilder = lastUpdated_.toBuilder();
              }
              lastUpdated_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(lastUpdated_);
                lastUpdated_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              to_ = s;
              break;
            }
            case 32: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                publisherCategories_ = newIntList();
                mutable_bitField0_ |= 0x00000002;
              }
              publisherCategories_.addInt(input.readSInt32());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
                publisherCategories_ = newIntList();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                publisherCategories_.addInt(input.readSInt32());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          publisherCategories_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return event.Event.internal_static_event_Greeting_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return event.Event.internal_static_event_Greeting_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              event.Event.Greeting.class, event.Event.Greeting.Builder.class);
    }

    private int bitField0_;
    public static final int FROM_FIELD_NUMBER = 1;
    private volatile java.lang.Object from_;
    /**
     * <code>string from = 1 [(.tagger.tags) = "parquet:&#92;"name=from, type=BYTE_ARRAY, encoding=PLAIN_DICTIONARY&#92;""];</code>
     * @return The from.
     */
    @java.lang.Override
    public java.lang.String getFrom() {
      java.lang.Object ref = from_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        from_ = s;
        return s;
      }
    }
    /**
     * <code>string from = 1 [(.tagger.tags) = "parquet:&#92;"name=from, type=BYTE_ARRAY, encoding=PLAIN_DICTIONARY&#92;""];</code>
     * @return The bytes for from.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFromBytes() {
      java.lang.Object ref = from_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        from_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAST_UPDATED_FIELD_NUMBER = 2;
    private com.google.protobuf.Timestamp lastUpdated_;
    /**
     * <code>.google.protobuf.Timestamp last_updated = 2 [(.tagger.tags) = "parquet:&#92;"name=last_updated, type=INT64, convertedtype=TIMESTAMP_MILLIS&#92;""];</code>
     * @return Whether the lastUpdated field is set.
     */
    @java.lang.Override
    public boolean hasLastUpdated() {
      return lastUpdated_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 2 [(.tagger.tags) = "parquet:&#92;"name=last_updated, type=INT64, convertedtype=TIMESTAMP_MILLIS&#92;""];</code>
     * @return The lastUpdated.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getLastUpdated() {
      return lastUpdated_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdated_;
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 2 [(.tagger.tags) = "parquet:&#92;"name=last_updated, type=INT64, convertedtype=TIMESTAMP_MILLIS&#92;""];</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getLastUpdatedOrBuilder() {
      return getLastUpdated();
    }

    public static final int TO_FIELD_NUMBER = 3;
    private volatile java.lang.Object to_;
    /**
     * <code>optional string to = 3 [(.tagger.tags) = "parquet:&#92;"name=to, type=BYTE_ARRAY, encoding=PLAIN_DICTIONARY&#92;""];</code>
     * @return Whether the to field is set.
     */
    @java.lang.Override
    public boolean hasTo() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string to = 3 [(.tagger.tags) = "parquet:&#92;"name=to, type=BYTE_ARRAY, encoding=PLAIN_DICTIONARY&#92;""];</code>
     * @return The to.
     */
    @java.lang.Override
    public java.lang.String getTo() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        to_ = s;
        return s;
      }
    }
    /**
     * <code>optional string to = 3 [(.tagger.tags) = "parquet:&#92;"name=to, type=BYTE_ARRAY, encoding=PLAIN_DICTIONARY&#92;""];</code>
     * @return The bytes for to.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getToBytes() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PUBLISHER_CATEGORIES_FIELD_NUMBER = 4;
    private com.google.protobuf.Internal.IntList publisherCategories_;
    /**
     * <code>repeated sint32 publisher_categories = 4 [(.tagger.tags) = "parquet:&#92;"name=publisher_categories, type=INT32 repetitiontype=REPEATED&#92;""];</code>
     * @return A list containing the publisherCategories.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getPublisherCategoriesList() {
      return publisherCategories_;
    }
    /**
     * <code>repeated sint32 publisher_categories = 4 [(.tagger.tags) = "parquet:&#92;"name=publisher_categories, type=INT32 repetitiontype=REPEATED&#92;""];</code>
     * @return The count of publisherCategories.
     */
    public int getPublisherCategoriesCount() {
      return publisherCategories_.size();
    }
    /**
     * <code>repeated sint32 publisher_categories = 4 [(.tagger.tags) = "parquet:&#92;"name=publisher_categories, type=INT32 repetitiontype=REPEATED&#92;""];</code>
     * @param index The index of the element to return.
     * @return The publisherCategories at the given index.
     */
    public int getPublisherCategories(int index) {
      return publisherCategories_.getInt(index);
    }
    private int publisherCategoriesMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!getFromBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, from_);
      }
      if (lastUpdated_ != null) {
        output.writeMessage(2, getLastUpdated());
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, to_);
      }
      if (getPublisherCategoriesList().size() > 0) {
        output.writeUInt32NoTag(34);
        output.writeUInt32NoTag(publisherCategoriesMemoizedSerializedSize);
      }
      for (int i = 0; i < publisherCategories_.size(); i++) {
        output.writeSInt32NoTag(publisherCategories_.getInt(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFromBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, from_);
      }
      if (lastUpdated_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getLastUpdated());
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, to_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < publisherCategories_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeSInt32SizeNoTag(publisherCategories_.getInt(i));
        }
        size += dataSize;
        if (!getPublisherCategoriesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        publisherCategoriesMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof event.Event.Greeting)) {
        return super.equals(obj);
      }
      event.Event.Greeting other = (event.Event.Greeting) obj;

      if (!getFrom()
          .equals(other.getFrom())) return false;
      if (hasLastUpdated() != other.hasLastUpdated()) return false;
      if (hasLastUpdated()) {
        if (!getLastUpdated()
            .equals(other.getLastUpdated())) return false;
      }
      if (hasTo() != other.hasTo()) return false;
      if (hasTo()) {
        if (!getTo()
            .equals(other.getTo())) return false;
      }
      if (!getPublisherCategoriesList()
          .equals(other.getPublisherCategoriesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FROM_FIELD_NUMBER;
      hash = (53 * hash) + getFrom().hashCode();
      if (hasLastUpdated()) {
        hash = (37 * hash) + LAST_UPDATED_FIELD_NUMBER;
        hash = (53 * hash) + getLastUpdated().hashCode();
      }
      if (hasTo()) {
        hash = (37 * hash) + TO_FIELD_NUMBER;
        hash = (53 * hash) + getTo().hashCode();
      }
      if (getPublisherCategoriesCount() > 0) {
        hash = (37 * hash) + PUBLISHER_CATEGORIES_FIELD_NUMBER;
        hash = (53 * hash) + getPublisherCategoriesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static event.Event.Greeting parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static event.Event.Greeting parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static event.Event.Greeting parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static event.Event.Greeting parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static event.Event.Greeting parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static event.Event.Greeting parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static event.Event.Greeting parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static event.Event.Greeting parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static event.Event.Greeting parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static event.Event.Greeting parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static event.Event.Greeting parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static event.Event.Greeting parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(event.Event.Greeting prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code event.Greeting}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:event.Greeting)
        event.Event.GreetingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return event.Event.internal_static_event_Greeting_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return event.Event.internal_static_event_Greeting_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                event.Event.Greeting.class, event.Event.Greeting.Builder.class);
      }

      // Construct using event.Event.Greeting.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        from_ = "";

        if (lastUpdatedBuilder_ == null) {
          lastUpdated_ = null;
        } else {
          lastUpdated_ = null;
          lastUpdatedBuilder_ = null;
        }
        to_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        publisherCategories_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return event.Event.internal_static_event_Greeting_descriptor;
      }

      @java.lang.Override
      public event.Event.Greeting getDefaultInstanceForType() {
        return event.Event.Greeting.getDefaultInstance();
      }

      @java.lang.Override
      public event.Event.Greeting build() {
        event.Event.Greeting result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public event.Event.Greeting buildPartial() {
        event.Event.Greeting result = new event.Event.Greeting(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.from_ = from_;
        if (lastUpdatedBuilder_ == null) {
          result.lastUpdated_ = lastUpdated_;
        } else {
          result.lastUpdated_ = lastUpdatedBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.to_ = to_;
        if (((bitField0_ & 0x00000002) != 0)) {
          publisherCategories_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.publisherCategories_ = publisherCategories_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof event.Event.Greeting) {
          return mergeFrom((event.Event.Greeting)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(event.Event.Greeting other) {
        if (other == event.Event.Greeting.getDefaultInstance()) return this;
        if (!other.getFrom().isEmpty()) {
          from_ = other.from_;
          onChanged();
        }
        if (other.hasLastUpdated()) {
          mergeLastUpdated(other.getLastUpdated());
        }
        if (other.hasTo()) {
          bitField0_ |= 0x00000001;
          to_ = other.to_;
          onChanged();
        }
        if (!other.publisherCategories_.isEmpty()) {
          if (publisherCategories_.isEmpty()) {
            publisherCategories_ = other.publisherCategories_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePublisherCategoriesIsMutable();
            publisherCategories_.addAll(other.publisherCategories_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        event.Event.Greeting parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (event.Event.Greeting) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object from_ = "";
      /**
       * <code>string from = 1 [(.tagger.tags) = "parquet:&#92;"name=from, type=BYTE_ARRAY, encoding=PLAIN_DICTIONARY&#92;""];</code>
       * @return The from.
       */
      public java.lang.String getFrom() {
        java.lang.Object ref = from_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          from_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string from = 1 [(.tagger.tags) = "parquet:&#92;"name=from, type=BYTE_ARRAY, encoding=PLAIN_DICTIONARY&#92;""];</code>
       * @return The bytes for from.
       */
      public com.google.protobuf.ByteString
          getFromBytes() {
        java.lang.Object ref = from_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          from_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string from = 1 [(.tagger.tags) = "parquet:&#92;"name=from, type=BYTE_ARRAY, encoding=PLAIN_DICTIONARY&#92;""];</code>
       * @param value The from to set.
       * @return This builder for chaining.
       */
      public Builder setFrom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        from_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string from = 1 [(.tagger.tags) = "parquet:&#92;"name=from, type=BYTE_ARRAY, encoding=PLAIN_DICTIONARY&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearFrom() {
        
        from_ = getDefaultInstance().getFrom();
        onChanged();
        return this;
      }
      /**
       * <code>string from = 1 [(.tagger.tags) = "parquet:&#92;"name=from, type=BYTE_ARRAY, encoding=PLAIN_DICTIONARY&#92;""];</code>
       * @param value The bytes for from to set.
       * @return This builder for chaining.
       */
      public Builder setFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        from_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp lastUpdated_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> lastUpdatedBuilder_;
      /**
       * <code>.google.protobuf.Timestamp last_updated = 2 [(.tagger.tags) = "parquet:&#92;"name=last_updated, type=INT64, convertedtype=TIMESTAMP_MILLIS&#92;""];</code>
       * @return Whether the lastUpdated field is set.
       */
      public boolean hasLastUpdated() {
        return lastUpdatedBuilder_ != null || lastUpdated_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp last_updated = 2 [(.tagger.tags) = "parquet:&#92;"name=last_updated, type=INT64, convertedtype=TIMESTAMP_MILLIS&#92;""];</code>
       * @return The lastUpdated.
       */
      public com.google.protobuf.Timestamp getLastUpdated() {
        if (lastUpdatedBuilder_ == null) {
          return lastUpdated_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdated_;
        } else {
          return lastUpdatedBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp last_updated = 2 [(.tagger.tags) = "parquet:&#92;"name=last_updated, type=INT64, convertedtype=TIMESTAMP_MILLIS&#92;""];</code>
       */
      public Builder setLastUpdated(com.google.protobuf.Timestamp value) {
        if (lastUpdatedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          lastUpdated_ = value;
          onChanged();
        } else {
          lastUpdatedBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp last_updated = 2 [(.tagger.tags) = "parquet:&#92;"name=last_updated, type=INT64, convertedtype=TIMESTAMP_MILLIS&#92;""];</code>
       */
      public Builder setLastUpdated(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (lastUpdatedBuilder_ == null) {
          lastUpdated_ = builderForValue.build();
          onChanged();
        } else {
          lastUpdatedBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp last_updated = 2 [(.tagger.tags) = "parquet:&#92;"name=last_updated, type=INT64, convertedtype=TIMESTAMP_MILLIS&#92;""];</code>
       */
      public Builder mergeLastUpdated(com.google.protobuf.Timestamp value) {
        if (lastUpdatedBuilder_ == null) {
          if (lastUpdated_ != null) {
            lastUpdated_ =
              com.google.protobuf.Timestamp.newBuilder(lastUpdated_).mergeFrom(value).buildPartial();
          } else {
            lastUpdated_ = value;
          }
          onChanged();
        } else {
          lastUpdatedBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp last_updated = 2 [(.tagger.tags) = "parquet:&#92;"name=last_updated, type=INT64, convertedtype=TIMESTAMP_MILLIS&#92;""];</code>
       */
      public Builder clearLastUpdated() {
        if (lastUpdatedBuilder_ == null) {
          lastUpdated_ = null;
          onChanged();
        } else {
          lastUpdated_ = null;
          lastUpdatedBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp last_updated = 2 [(.tagger.tags) = "parquet:&#92;"name=last_updated, type=INT64, convertedtype=TIMESTAMP_MILLIS&#92;""];</code>
       */
      public com.google.protobuf.Timestamp.Builder getLastUpdatedBuilder() {
        
        onChanged();
        return getLastUpdatedFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp last_updated = 2 [(.tagger.tags) = "parquet:&#92;"name=last_updated, type=INT64, convertedtype=TIMESTAMP_MILLIS&#92;""];</code>
       */
      public com.google.protobuf.TimestampOrBuilder getLastUpdatedOrBuilder() {
        if (lastUpdatedBuilder_ != null) {
          return lastUpdatedBuilder_.getMessageOrBuilder();
        } else {
          return lastUpdated_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdated_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp last_updated = 2 [(.tagger.tags) = "parquet:&#92;"name=last_updated, type=INT64, convertedtype=TIMESTAMP_MILLIS&#92;""];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getLastUpdatedFieldBuilder() {
        if (lastUpdatedBuilder_ == null) {
          lastUpdatedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getLastUpdated(),
                  getParentForChildren(),
                  isClean());
          lastUpdated_ = null;
        }
        return lastUpdatedBuilder_;
      }

      private java.lang.Object to_ = "";
      /**
       * <code>optional string to = 3 [(.tagger.tags) = "parquet:&#92;"name=to, type=BYTE_ARRAY, encoding=PLAIN_DICTIONARY&#92;""];</code>
       * @return Whether the to field is set.
       */
      public boolean hasTo() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string to = 3 [(.tagger.tags) = "parquet:&#92;"name=to, type=BYTE_ARRAY, encoding=PLAIN_DICTIONARY&#92;""];</code>
       * @return The to.
       */
      public java.lang.String getTo() {
        java.lang.Object ref = to_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          to_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string to = 3 [(.tagger.tags) = "parquet:&#92;"name=to, type=BYTE_ARRAY, encoding=PLAIN_DICTIONARY&#92;""];</code>
       * @return The bytes for to.
       */
      public com.google.protobuf.ByteString
          getToBytes() {
        java.lang.Object ref = to_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          to_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string to = 3 [(.tagger.tags) = "parquet:&#92;"name=to, type=BYTE_ARRAY, encoding=PLAIN_DICTIONARY&#92;""];</code>
       * @param value The to to set.
       * @return This builder for chaining.
       */
      public Builder setTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        to_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string to = 3 [(.tagger.tags) = "parquet:&#92;"name=to, type=BYTE_ARRAY, encoding=PLAIN_DICTIONARY&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearTo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        to_ = getDefaultInstance().getTo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string to = 3 [(.tagger.tags) = "parquet:&#92;"name=to, type=BYTE_ARRAY, encoding=PLAIN_DICTIONARY&#92;""];</code>
       * @param value The bytes for to to set.
       * @return This builder for chaining.
       */
      public Builder setToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000001;
        to_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList publisherCategories_ = emptyIntList();
      private void ensurePublisherCategoriesIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          publisherCategories_ = mutableCopy(publisherCategories_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated sint32 publisher_categories = 4 [(.tagger.tags) = "parquet:&#92;"name=publisher_categories, type=INT32 repetitiontype=REPEATED&#92;""];</code>
       * @return A list containing the publisherCategories.
       */
      public java.util.List<java.lang.Integer>
          getPublisherCategoriesList() {
        return ((bitField0_ & 0x00000002) != 0) ?
                 java.util.Collections.unmodifiableList(publisherCategories_) : publisherCategories_;
      }
      /**
       * <code>repeated sint32 publisher_categories = 4 [(.tagger.tags) = "parquet:&#92;"name=publisher_categories, type=INT32 repetitiontype=REPEATED&#92;""];</code>
       * @return The count of publisherCategories.
       */
      public int getPublisherCategoriesCount() {
        return publisherCategories_.size();
      }
      /**
       * <code>repeated sint32 publisher_categories = 4 [(.tagger.tags) = "parquet:&#92;"name=publisher_categories, type=INT32 repetitiontype=REPEATED&#92;""];</code>
       * @param index The index of the element to return.
       * @return The publisherCategories at the given index.
       */
      public int getPublisherCategories(int index) {
        return publisherCategories_.getInt(index);
      }
      /**
       * <code>repeated sint32 publisher_categories = 4 [(.tagger.tags) = "parquet:&#92;"name=publisher_categories, type=INT32 repetitiontype=REPEATED&#92;""];</code>
       * @param index The index to set the value at.
       * @param value The publisherCategories to set.
       * @return This builder for chaining.
       */
      public Builder setPublisherCategories(
          int index, int value) {
        ensurePublisherCategoriesIsMutable();
        publisherCategories_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sint32 publisher_categories = 4 [(.tagger.tags) = "parquet:&#92;"name=publisher_categories, type=INT32 repetitiontype=REPEATED&#92;""];</code>
       * @param value The publisherCategories to add.
       * @return This builder for chaining.
       */
      public Builder addPublisherCategories(int value) {
        ensurePublisherCategoriesIsMutable();
        publisherCategories_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sint32 publisher_categories = 4 [(.tagger.tags) = "parquet:&#92;"name=publisher_categories, type=INT32 repetitiontype=REPEATED&#92;""];</code>
       * @param values The publisherCategories to add.
       * @return This builder for chaining.
       */
      public Builder addAllPublisherCategories(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensurePublisherCategoriesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, publisherCategories_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sint32 publisher_categories = 4 [(.tagger.tags) = "parquet:&#92;"name=publisher_categories, type=INT32 repetitiontype=REPEATED&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearPublisherCategories() {
        publisherCategories_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:event.Greeting)
    }

    // @@protoc_insertion_point(class_scope:event.Greeting)
    private static final event.Event.Greeting DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new event.Event.Greeting();
    }

    public static event.Event.Greeting getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Greeting>
        PARSER = new com.google.protobuf.AbstractParser<Greeting>() {
      @java.lang.Override
      public Greeting parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Greeting(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Greeting> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Greeting> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public event.Event.Greeting getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GreetingSimpleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:event.GreetingSimple)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string from = 1 [(.tagger.tags) = "parquet:&#92;"name=from,type=BYTE_ARRAY, convertedtype=UTF8, encoding=PLAIN_DICTIONARY&#92;""];</code>
     * @return The from.
     */
    java.lang.String getFrom();
    /**
     * <code>string from = 1 [(.tagger.tags) = "parquet:&#92;"name=from,type=BYTE_ARRAY, convertedtype=UTF8, encoding=PLAIN_DICTIONARY&#92;""];</code>
     * @return The bytes for from.
     */
    com.google.protobuf.ByteString
        getFromBytes();

    /**
     * <code>int64 last_updated = 2 [(.tagger.tags) = "parquet:&#92;"name=last_updated, type=INT64, convertedtype=TIMESTAMP_MILLIS&#92;""];</code>
     * @return The lastUpdated.
     */
    long getLastUpdated();

    /**
     * <code>optional string to = 3 [(.tagger.tags) = "parquet:&#92;"name=to,type=BYTE_ARRAY, convertedtype=UTF8, encoding=PLAIN_DICTIONARY&#92;""];</code>
     * @return Whether the to field is set.
     */
    boolean hasTo();
    /**
     * <code>optional string to = 3 [(.tagger.tags) = "parquet:&#92;"name=to,type=BYTE_ARRAY, convertedtype=UTF8, encoding=PLAIN_DICTIONARY&#92;""];</code>
     * @return The to.
     */
    java.lang.String getTo();
    /**
     * <code>optional string to = 3 [(.tagger.tags) = "parquet:&#92;"name=to,type=BYTE_ARRAY, convertedtype=UTF8, encoding=PLAIN_DICTIONARY&#92;""];</code>
     * @return The bytes for to.
     */
    com.google.protobuf.ByteString
        getToBytes();

    /**
     * <code>repeated sint32 publisher_categories = 4 [(.tagger.tags) = "parquet:&#92;"name=publisher_categories, type=INT32, repetitiontype=REPEATED&#92;""];</code>
     * @return A list containing the publisherCategories.
     */
    java.util.List<java.lang.Integer> getPublisherCategoriesList();
    /**
     * <code>repeated sint32 publisher_categories = 4 [(.tagger.tags) = "parquet:&#92;"name=publisher_categories, type=INT32, repetitiontype=REPEATED&#92;""];</code>
     * @return The count of publisherCategories.
     */
    int getPublisherCategoriesCount();
    /**
     * <code>repeated sint32 publisher_categories = 4 [(.tagger.tags) = "parquet:&#92;"name=publisher_categories, type=INT32, repetitiontype=REPEATED&#92;""];</code>
     * @param index The index of the element to return.
     * @return The publisherCategories at the given index.
     */
    int getPublisherCategories(int index);
  }
  /**
   * Protobuf type {@code event.GreetingSimple}
   */
  public static final class GreetingSimple extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:event.GreetingSimple)
      GreetingSimpleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GreetingSimple.newBuilder() to construct.
    private GreetingSimple(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GreetingSimple() {
      from_ = "";
      to_ = "";
      publisherCategories_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GreetingSimple();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GreetingSimple(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              from_ = s;
              break;
            }
            case 16: {

              lastUpdated_ = input.readInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              to_ = s;
              break;
            }
            case 32: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                publisherCategories_ = newIntList();
                mutable_bitField0_ |= 0x00000002;
              }
              publisherCategories_.addInt(input.readSInt32());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
                publisherCategories_ = newIntList();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                publisherCategories_.addInt(input.readSInt32());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          publisherCategories_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return event.Event.internal_static_event_GreetingSimple_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return event.Event.internal_static_event_GreetingSimple_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              event.Event.GreetingSimple.class, event.Event.GreetingSimple.Builder.class);
    }

    private int bitField0_;
    public static final int FROM_FIELD_NUMBER = 1;
    private volatile java.lang.Object from_;
    /**
     * <code>string from = 1 [(.tagger.tags) = "parquet:&#92;"name=from,type=BYTE_ARRAY, convertedtype=UTF8, encoding=PLAIN_DICTIONARY&#92;""];</code>
     * @return The from.
     */
    @java.lang.Override
    public java.lang.String getFrom() {
      java.lang.Object ref = from_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        from_ = s;
        return s;
      }
    }
    /**
     * <code>string from = 1 [(.tagger.tags) = "parquet:&#92;"name=from,type=BYTE_ARRAY, convertedtype=UTF8, encoding=PLAIN_DICTIONARY&#92;""];</code>
     * @return The bytes for from.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFromBytes() {
      java.lang.Object ref = from_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        from_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAST_UPDATED_FIELD_NUMBER = 2;
    private long lastUpdated_;
    /**
     * <code>int64 last_updated = 2 [(.tagger.tags) = "parquet:&#92;"name=last_updated, type=INT64, convertedtype=TIMESTAMP_MILLIS&#92;""];</code>
     * @return The lastUpdated.
     */
    @java.lang.Override
    public long getLastUpdated() {
      return lastUpdated_;
    }

    public static final int TO_FIELD_NUMBER = 3;
    private volatile java.lang.Object to_;
    /**
     * <code>optional string to = 3 [(.tagger.tags) = "parquet:&#92;"name=to,type=BYTE_ARRAY, convertedtype=UTF8, encoding=PLAIN_DICTIONARY&#92;""];</code>
     * @return Whether the to field is set.
     */
    @java.lang.Override
    public boolean hasTo() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string to = 3 [(.tagger.tags) = "parquet:&#92;"name=to,type=BYTE_ARRAY, convertedtype=UTF8, encoding=PLAIN_DICTIONARY&#92;""];</code>
     * @return The to.
     */
    @java.lang.Override
    public java.lang.String getTo() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        to_ = s;
        return s;
      }
    }
    /**
     * <code>optional string to = 3 [(.tagger.tags) = "parquet:&#92;"name=to,type=BYTE_ARRAY, convertedtype=UTF8, encoding=PLAIN_DICTIONARY&#92;""];</code>
     * @return The bytes for to.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getToBytes() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PUBLISHER_CATEGORIES_FIELD_NUMBER = 4;
    private com.google.protobuf.Internal.IntList publisherCategories_;
    /**
     * <code>repeated sint32 publisher_categories = 4 [(.tagger.tags) = "parquet:&#92;"name=publisher_categories, type=INT32, repetitiontype=REPEATED&#92;""];</code>
     * @return A list containing the publisherCategories.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getPublisherCategoriesList() {
      return publisherCategories_;
    }
    /**
     * <code>repeated sint32 publisher_categories = 4 [(.tagger.tags) = "parquet:&#92;"name=publisher_categories, type=INT32, repetitiontype=REPEATED&#92;""];</code>
     * @return The count of publisherCategories.
     */
    public int getPublisherCategoriesCount() {
      return publisherCategories_.size();
    }
    /**
     * <code>repeated sint32 publisher_categories = 4 [(.tagger.tags) = "parquet:&#92;"name=publisher_categories, type=INT32, repetitiontype=REPEATED&#92;""];</code>
     * @param index The index of the element to return.
     * @return The publisherCategories at the given index.
     */
    public int getPublisherCategories(int index) {
      return publisherCategories_.getInt(index);
    }
    private int publisherCategoriesMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!getFromBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, from_);
      }
      if (lastUpdated_ != 0L) {
        output.writeInt64(2, lastUpdated_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, to_);
      }
      if (getPublisherCategoriesList().size() > 0) {
        output.writeUInt32NoTag(34);
        output.writeUInt32NoTag(publisherCategoriesMemoizedSerializedSize);
      }
      for (int i = 0; i < publisherCategories_.size(); i++) {
        output.writeSInt32NoTag(publisherCategories_.getInt(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFromBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, from_);
      }
      if (lastUpdated_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, lastUpdated_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, to_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < publisherCategories_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeSInt32SizeNoTag(publisherCategories_.getInt(i));
        }
        size += dataSize;
        if (!getPublisherCategoriesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        publisherCategoriesMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof event.Event.GreetingSimple)) {
        return super.equals(obj);
      }
      event.Event.GreetingSimple other = (event.Event.GreetingSimple) obj;

      if (!getFrom()
          .equals(other.getFrom())) return false;
      if (getLastUpdated()
          != other.getLastUpdated()) return false;
      if (hasTo() != other.hasTo()) return false;
      if (hasTo()) {
        if (!getTo()
            .equals(other.getTo())) return false;
      }
      if (!getPublisherCategoriesList()
          .equals(other.getPublisherCategoriesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FROM_FIELD_NUMBER;
      hash = (53 * hash) + getFrom().hashCode();
      hash = (37 * hash) + LAST_UPDATED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastUpdated());
      if (hasTo()) {
        hash = (37 * hash) + TO_FIELD_NUMBER;
        hash = (53 * hash) + getTo().hashCode();
      }
      if (getPublisherCategoriesCount() > 0) {
        hash = (37 * hash) + PUBLISHER_CATEGORIES_FIELD_NUMBER;
        hash = (53 * hash) + getPublisherCategoriesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static event.Event.GreetingSimple parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static event.Event.GreetingSimple parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static event.Event.GreetingSimple parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static event.Event.GreetingSimple parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static event.Event.GreetingSimple parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static event.Event.GreetingSimple parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static event.Event.GreetingSimple parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static event.Event.GreetingSimple parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static event.Event.GreetingSimple parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static event.Event.GreetingSimple parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static event.Event.GreetingSimple parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static event.Event.GreetingSimple parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(event.Event.GreetingSimple prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code event.GreetingSimple}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:event.GreetingSimple)
        event.Event.GreetingSimpleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return event.Event.internal_static_event_GreetingSimple_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return event.Event.internal_static_event_GreetingSimple_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                event.Event.GreetingSimple.class, event.Event.GreetingSimple.Builder.class);
      }

      // Construct using event.Event.GreetingSimple.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        from_ = "";

        lastUpdated_ = 0L;

        to_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        publisherCategories_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return event.Event.internal_static_event_GreetingSimple_descriptor;
      }

      @java.lang.Override
      public event.Event.GreetingSimple getDefaultInstanceForType() {
        return event.Event.GreetingSimple.getDefaultInstance();
      }

      @java.lang.Override
      public event.Event.GreetingSimple build() {
        event.Event.GreetingSimple result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public event.Event.GreetingSimple buildPartial() {
        event.Event.GreetingSimple result = new event.Event.GreetingSimple(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.from_ = from_;
        result.lastUpdated_ = lastUpdated_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.to_ = to_;
        if (((bitField0_ & 0x00000002) != 0)) {
          publisherCategories_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.publisherCategories_ = publisherCategories_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof event.Event.GreetingSimple) {
          return mergeFrom((event.Event.GreetingSimple)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(event.Event.GreetingSimple other) {
        if (other == event.Event.GreetingSimple.getDefaultInstance()) return this;
        if (!other.getFrom().isEmpty()) {
          from_ = other.from_;
          onChanged();
        }
        if (other.getLastUpdated() != 0L) {
          setLastUpdated(other.getLastUpdated());
        }
        if (other.hasTo()) {
          bitField0_ |= 0x00000001;
          to_ = other.to_;
          onChanged();
        }
        if (!other.publisherCategories_.isEmpty()) {
          if (publisherCategories_.isEmpty()) {
            publisherCategories_ = other.publisherCategories_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePublisherCategoriesIsMutable();
            publisherCategories_.addAll(other.publisherCategories_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        event.Event.GreetingSimple parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (event.Event.GreetingSimple) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object from_ = "";
      /**
       * <code>string from = 1 [(.tagger.tags) = "parquet:&#92;"name=from,type=BYTE_ARRAY, convertedtype=UTF8, encoding=PLAIN_DICTIONARY&#92;""];</code>
       * @return The from.
       */
      public java.lang.String getFrom() {
        java.lang.Object ref = from_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          from_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string from = 1 [(.tagger.tags) = "parquet:&#92;"name=from,type=BYTE_ARRAY, convertedtype=UTF8, encoding=PLAIN_DICTIONARY&#92;""];</code>
       * @return The bytes for from.
       */
      public com.google.protobuf.ByteString
          getFromBytes() {
        java.lang.Object ref = from_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          from_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string from = 1 [(.tagger.tags) = "parquet:&#92;"name=from,type=BYTE_ARRAY, convertedtype=UTF8, encoding=PLAIN_DICTIONARY&#92;""];</code>
       * @param value The from to set.
       * @return This builder for chaining.
       */
      public Builder setFrom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        from_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string from = 1 [(.tagger.tags) = "parquet:&#92;"name=from,type=BYTE_ARRAY, convertedtype=UTF8, encoding=PLAIN_DICTIONARY&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearFrom() {
        
        from_ = getDefaultInstance().getFrom();
        onChanged();
        return this;
      }
      /**
       * <code>string from = 1 [(.tagger.tags) = "parquet:&#92;"name=from,type=BYTE_ARRAY, convertedtype=UTF8, encoding=PLAIN_DICTIONARY&#92;""];</code>
       * @param value The bytes for from to set.
       * @return This builder for chaining.
       */
      public Builder setFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        from_ = value;
        onChanged();
        return this;
      }

      private long lastUpdated_ ;
      /**
       * <code>int64 last_updated = 2 [(.tagger.tags) = "parquet:&#92;"name=last_updated, type=INT64, convertedtype=TIMESTAMP_MILLIS&#92;""];</code>
       * @return The lastUpdated.
       */
      @java.lang.Override
      public long getLastUpdated() {
        return lastUpdated_;
      }
      /**
       * <code>int64 last_updated = 2 [(.tagger.tags) = "parquet:&#92;"name=last_updated, type=INT64, convertedtype=TIMESTAMP_MILLIS&#92;""];</code>
       * @param value The lastUpdated to set.
       * @return This builder for chaining.
       */
      public Builder setLastUpdated(long value) {
        
        lastUpdated_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 last_updated = 2 [(.tagger.tags) = "parquet:&#92;"name=last_updated, type=INT64, convertedtype=TIMESTAMP_MILLIS&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearLastUpdated() {
        
        lastUpdated_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object to_ = "";
      /**
       * <code>optional string to = 3 [(.tagger.tags) = "parquet:&#92;"name=to,type=BYTE_ARRAY, convertedtype=UTF8, encoding=PLAIN_DICTIONARY&#92;""];</code>
       * @return Whether the to field is set.
       */
      public boolean hasTo() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string to = 3 [(.tagger.tags) = "parquet:&#92;"name=to,type=BYTE_ARRAY, convertedtype=UTF8, encoding=PLAIN_DICTIONARY&#92;""];</code>
       * @return The to.
       */
      public java.lang.String getTo() {
        java.lang.Object ref = to_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          to_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string to = 3 [(.tagger.tags) = "parquet:&#92;"name=to,type=BYTE_ARRAY, convertedtype=UTF8, encoding=PLAIN_DICTIONARY&#92;""];</code>
       * @return The bytes for to.
       */
      public com.google.protobuf.ByteString
          getToBytes() {
        java.lang.Object ref = to_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          to_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string to = 3 [(.tagger.tags) = "parquet:&#92;"name=to,type=BYTE_ARRAY, convertedtype=UTF8, encoding=PLAIN_DICTIONARY&#92;""];</code>
       * @param value The to to set.
       * @return This builder for chaining.
       */
      public Builder setTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        to_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string to = 3 [(.tagger.tags) = "parquet:&#92;"name=to,type=BYTE_ARRAY, convertedtype=UTF8, encoding=PLAIN_DICTIONARY&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearTo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        to_ = getDefaultInstance().getTo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string to = 3 [(.tagger.tags) = "parquet:&#92;"name=to,type=BYTE_ARRAY, convertedtype=UTF8, encoding=PLAIN_DICTIONARY&#92;""];</code>
       * @param value The bytes for to to set.
       * @return This builder for chaining.
       */
      public Builder setToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000001;
        to_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList publisherCategories_ = emptyIntList();
      private void ensurePublisherCategoriesIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          publisherCategories_ = mutableCopy(publisherCategories_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated sint32 publisher_categories = 4 [(.tagger.tags) = "parquet:&#92;"name=publisher_categories, type=INT32, repetitiontype=REPEATED&#92;""];</code>
       * @return A list containing the publisherCategories.
       */
      public java.util.List<java.lang.Integer>
          getPublisherCategoriesList() {
        return ((bitField0_ & 0x00000002) != 0) ?
                 java.util.Collections.unmodifiableList(publisherCategories_) : publisherCategories_;
      }
      /**
       * <code>repeated sint32 publisher_categories = 4 [(.tagger.tags) = "parquet:&#92;"name=publisher_categories, type=INT32, repetitiontype=REPEATED&#92;""];</code>
       * @return The count of publisherCategories.
       */
      public int getPublisherCategoriesCount() {
        return publisherCategories_.size();
      }
      /**
       * <code>repeated sint32 publisher_categories = 4 [(.tagger.tags) = "parquet:&#92;"name=publisher_categories, type=INT32, repetitiontype=REPEATED&#92;""];</code>
       * @param index The index of the element to return.
       * @return The publisherCategories at the given index.
       */
      public int getPublisherCategories(int index) {
        return publisherCategories_.getInt(index);
      }
      /**
       * <code>repeated sint32 publisher_categories = 4 [(.tagger.tags) = "parquet:&#92;"name=publisher_categories, type=INT32, repetitiontype=REPEATED&#92;""];</code>
       * @param index The index to set the value at.
       * @param value The publisherCategories to set.
       * @return This builder for chaining.
       */
      public Builder setPublisherCategories(
          int index, int value) {
        ensurePublisherCategoriesIsMutable();
        publisherCategories_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sint32 publisher_categories = 4 [(.tagger.tags) = "parquet:&#92;"name=publisher_categories, type=INT32, repetitiontype=REPEATED&#92;""];</code>
       * @param value The publisherCategories to add.
       * @return This builder for chaining.
       */
      public Builder addPublisherCategories(int value) {
        ensurePublisherCategoriesIsMutable();
        publisherCategories_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sint32 publisher_categories = 4 [(.tagger.tags) = "parquet:&#92;"name=publisher_categories, type=INT32, repetitiontype=REPEATED&#92;""];</code>
       * @param values The publisherCategories to add.
       * @return This builder for chaining.
       */
      public Builder addAllPublisherCategories(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensurePublisherCategoriesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, publisherCategories_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sint32 publisher_categories = 4 [(.tagger.tags) = "parquet:&#92;"name=publisher_categories, type=INT32, repetitiontype=REPEATED&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearPublisherCategories() {
        publisherCategories_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:event.GreetingSimple)
    }

    // @@protoc_insertion_point(class_scope:event.GreetingSimple)
    private static final event.Event.GreetingSimple DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new event.Event.GreetingSimple();
    }

    public static event.Event.GreetingSimple getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GreetingSimple>
        PARSER = new com.google.protobuf.AbstractParser<GreetingSimple>() {
      @java.lang.Override
      public GreetingSimple parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GreetingSimple(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GreetingSimple> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GreetingSimple> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public event.Event.GreetingSimple getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_event_Greeting_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_event_Greeting_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_event_GreetingSimple_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_event_GreetingSimple_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013event.proto\022\005event\032\037google/protobuf/ti" +
      "mestamp.proto\032\014tagger.proto\"\246\003\n\010Greeting" +
      "\022R\n\004from\030\001 \001(\tBD\232\204\236\003?parquet:\"name=from," +
      " type=BYTE_ARRAY, encoding=PLAIN_DICTION" +
      "ARY\"\022~\n\014last_updated\030\002 \001(\0132\032.google.prot" +
      "obuf.TimestampBL\232\204\236\003Gparquet:\"name=last_" +
      "updated, type=INT64, convertedtype=TIMES" +
      "TAMP_MILLIS\"\022S\n\002to\030\003 \001(\tBB\232\204\236\003=parquet:\"" +
      "name=to, type=BYTE_ARRAY, encoding=PLAIN" +
      "_DICTIONARY\"H\000\210\001\001\022j\n\024publisher_categorie" +
      "s\030\004 \003(\021BL\232\204\236\003Gparquet:\"name=publisher_ca" +
      "tegories, type=INT32 repetitiontype=REPE" +
      "ATED\"B\005\n\003_to\"\267\003\n\016GreetingSimple\022e\n\004from\030" +
      "\001 \001(\tBW\232\204\236\003Rparquet:\"name=from,type=BYTE" +
      "_ARRAY, convertedtype=UTF8, encoding=PLA" +
      "IN_DICTIONARY\"\022b\n\014last_updated\030\002 \001(\003BL\232\204" +
      "\236\003Gparquet:\"name=last_updated, type=INT6" +
      "4, convertedtype=TIMESTAMP_MILLIS\"\022f\n\002to" +
      "\030\003 \001(\tBU\232\204\236\003Pparquet:\"name=to,type=BYTE_" +
      "ARRAY, convertedtype=UTF8, encoding=PLAI" +
      "N_DICTIONARY\"H\000\210\001\001\022k\n\024publisher_categori" +
      "es\030\004 \003(\021BM\232\204\236\003Hparquet:\"name=publisher_c" +
      "ategories, type=INT32, repetitiontype=RE" +
      "PEATED\"B\005\n\003_toB.Z,github.com/davidae/pro" +
      "to-definition/proto/gob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          tagger.Tagger.getDescriptor(),
        });
    internal_static_event_Greeting_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_event_Greeting_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_event_Greeting_descriptor,
        new java.lang.String[] { "From", "LastUpdated", "To", "PublisherCategories", "To", });
    internal_static_event_GreetingSimple_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_event_GreetingSimple_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_event_GreetingSimple_descriptor,
        new java.lang.String[] { "From", "LastUpdated", "To", "PublisherCategories", "To", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(tagger.Tagger.tags);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.TimestampProto.getDescriptor();
    tagger.Tagger.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
