// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event_wrapper.proto

package event;

public final class EventWrapper {
  private EventWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GreetingWrappOrBuilder extends
      // @@protoc_insertion_point(interface_extends:event.GreetingWrapp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.StringValue from = 1;</code>
     * @return Whether the from field is set.
     */
    boolean hasFrom();
    /**
     * <code>.google.protobuf.StringValue from = 1;</code>
     * @return The from.
     */
    com.google.protobuf.StringValue getFrom();
    /**
     * <code>.google.protobuf.StringValue from = 1;</code>
     */
    com.google.protobuf.StringValueOrBuilder getFromOrBuilder();

    /**
     * <code>.google.protobuf.Timestamp last_updated = 2;</code>
     * @return Whether the lastUpdated field is set.
     */
    boolean hasLastUpdated();
    /**
     * <code>.google.protobuf.Timestamp last_updated = 2;</code>
     * @return The lastUpdated.
     */
    com.google.protobuf.Timestamp getLastUpdated();
    /**
     * <code>.google.protobuf.Timestamp last_updated = 2;</code>
     */
    com.google.protobuf.TimestampOrBuilder getLastUpdatedOrBuilder();

    /**
     * <code>.google.protobuf.StringValue to = 3;</code>
     * @return Whether the to field is set.
     */
    boolean hasTo();
    /**
     * <code>.google.protobuf.StringValue to = 3;</code>
     * @return The to.
     */
    com.google.protobuf.StringValue getTo();
    /**
     * <code>.google.protobuf.StringValue to = 3;</code>
     */
    com.google.protobuf.StringValueOrBuilder getToOrBuilder();

    /**
     * <code>repeated sint32 publisher_categories = 4;</code>
     * @return A list containing the publisherCategories.
     */
    java.util.List<java.lang.Integer> getPublisherCategoriesList();
    /**
     * <code>repeated sint32 publisher_categories = 4;</code>
     * @return The count of publisherCategories.
     */
    int getPublisherCategoriesCount();
    /**
     * <code>repeated sint32 publisher_categories = 4;</code>
     * @param index The index of the element to return.
     * @return The publisherCategories at the given index.
     */
    int getPublisherCategories(int index);

    /**
     * <pre>
     * always set this to "true" when null
     * </pre>
     *
     * <code>bool baz_null = 5;</code>
     * @return Whether the bazNull field is set.
     */
    boolean hasBazNull();
    /**
     * <pre>
     * always set this to "true" when null
     * </pre>
     *
     * <code>bool baz_null = 5;</code>
     * @return The bazNull.
     */
    boolean getBazNull();

    /**
     * <code>int32 baz_value = 6;</code>
     * @return Whether the bazValue field is set.
     */
    boolean hasBazValue();
    /**
     * <code>int32 baz_value = 6;</code>
     * @return The bazValue.
     */
    int getBazValue();

    public event.EventWrapper.GreetingWrapp.BazCase getBazCase();
  }
  /**
   * Protobuf type {@code event.GreetingWrapp}
   */
  public static final class GreetingWrapp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:event.GreetingWrapp)
      GreetingWrappOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GreetingWrapp.newBuilder() to construct.
    private GreetingWrapp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GreetingWrapp() {
      publisherCategories_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GreetingWrapp();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GreetingWrapp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (from_ != null) {
                subBuilder = from_.toBuilder();
              }
              from_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(from_);
                from_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (lastUpdated_ != null) {
                subBuilder = lastUpdated_.toBuilder();
              }
              lastUpdated_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(lastUpdated_);
                lastUpdated_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (to_ != null) {
                subBuilder = to_.toBuilder();
              }
              to_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(to_);
                to_ = subBuilder.buildPartial();
              }

              break;
            }
            case 32: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                publisherCategories_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              publisherCategories_.addInt(input.readSInt32());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                publisherCategories_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                publisherCategories_.addInt(input.readSInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 40: {
              bazCase_ = 5;
              baz_ = input.readBool();
              break;
            }
            case 48: {
              bazCase_ = 6;
              baz_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          publisherCategories_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return event.EventWrapper.internal_static_event_GreetingWrapp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return event.EventWrapper.internal_static_event_GreetingWrapp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              event.EventWrapper.GreetingWrapp.class, event.EventWrapper.GreetingWrapp.Builder.class);
    }

    private int bazCase_ = 0;
    private java.lang.Object baz_;
    public enum BazCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      BAZ_NULL(5),
      BAZ_VALUE(6),
      BAZ_NOT_SET(0);
      private final int value;
      private BazCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static BazCase valueOf(int value) {
        return forNumber(value);
      }

      public static BazCase forNumber(int value) {
        switch (value) {
          case 5: return BAZ_NULL;
          case 6: return BAZ_VALUE;
          case 0: return BAZ_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public BazCase
    getBazCase() {
      return BazCase.forNumber(
          bazCase_);
    }

    public static final int FROM_FIELD_NUMBER = 1;
    private com.google.protobuf.StringValue from_;
    /**
     * <code>.google.protobuf.StringValue from = 1;</code>
     * @return Whether the from field is set.
     */
    @java.lang.Override
    public boolean hasFrom() {
      return from_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue from = 1;</code>
     * @return The from.
     */
    @java.lang.Override
    public com.google.protobuf.StringValue getFrom() {
      return from_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : from_;
    }
    /**
     * <code>.google.protobuf.StringValue from = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.StringValueOrBuilder getFromOrBuilder() {
      return getFrom();
    }

    public static final int LAST_UPDATED_FIELD_NUMBER = 2;
    private com.google.protobuf.Timestamp lastUpdated_;
    /**
     * <code>.google.protobuf.Timestamp last_updated = 2;</code>
     * @return Whether the lastUpdated field is set.
     */
    @java.lang.Override
    public boolean hasLastUpdated() {
      return lastUpdated_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 2;</code>
     * @return The lastUpdated.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getLastUpdated() {
      return lastUpdated_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdated_;
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getLastUpdatedOrBuilder() {
      return getLastUpdated();
    }

    public static final int TO_FIELD_NUMBER = 3;
    private com.google.protobuf.StringValue to_;
    /**
     * <code>.google.protobuf.StringValue to = 3;</code>
     * @return Whether the to field is set.
     */
    @java.lang.Override
    public boolean hasTo() {
      return to_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue to = 3;</code>
     * @return The to.
     */
    @java.lang.Override
    public com.google.protobuf.StringValue getTo() {
      return to_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : to_;
    }
    /**
     * <code>.google.protobuf.StringValue to = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.StringValueOrBuilder getToOrBuilder() {
      return getTo();
    }

    public static final int PUBLISHER_CATEGORIES_FIELD_NUMBER = 4;
    private com.google.protobuf.Internal.IntList publisherCategories_;
    /**
     * <code>repeated sint32 publisher_categories = 4;</code>
     * @return A list containing the publisherCategories.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getPublisherCategoriesList() {
      return publisherCategories_;
    }
    /**
     * <code>repeated sint32 publisher_categories = 4;</code>
     * @return The count of publisherCategories.
     */
    public int getPublisherCategoriesCount() {
      return publisherCategories_.size();
    }
    /**
     * <code>repeated sint32 publisher_categories = 4;</code>
     * @param index The index of the element to return.
     * @return The publisherCategories at the given index.
     */
    public int getPublisherCategories(int index) {
      return publisherCategories_.getInt(index);
    }
    private int publisherCategoriesMemoizedSerializedSize = -1;

    public static final int BAZ_NULL_FIELD_NUMBER = 5;
    /**
     * <pre>
     * always set this to "true" when null
     * </pre>
     *
     * <code>bool baz_null = 5;</code>
     * @return Whether the bazNull field is set.
     */
    @java.lang.Override
    public boolean hasBazNull() {
      return bazCase_ == 5;
    }
    /**
     * <pre>
     * always set this to "true" when null
     * </pre>
     *
     * <code>bool baz_null = 5;</code>
     * @return The bazNull.
     */
    @java.lang.Override
    public boolean getBazNull() {
      if (bazCase_ == 5) {
        return (java.lang.Boolean) baz_;
      }
      return false;
    }

    public static final int BAZ_VALUE_FIELD_NUMBER = 6;
    /**
     * <code>int32 baz_value = 6;</code>
     * @return Whether the bazValue field is set.
     */
    @java.lang.Override
    public boolean hasBazValue() {
      return bazCase_ == 6;
    }
    /**
     * <code>int32 baz_value = 6;</code>
     * @return The bazValue.
     */
    @java.lang.Override
    public int getBazValue() {
      if (bazCase_ == 6) {
        return (java.lang.Integer) baz_;
      }
      return 0;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (from_ != null) {
        output.writeMessage(1, getFrom());
      }
      if (lastUpdated_ != null) {
        output.writeMessage(2, getLastUpdated());
      }
      if (to_ != null) {
        output.writeMessage(3, getTo());
      }
      if (getPublisherCategoriesList().size() > 0) {
        output.writeUInt32NoTag(34);
        output.writeUInt32NoTag(publisherCategoriesMemoizedSerializedSize);
      }
      for (int i = 0; i < publisherCategories_.size(); i++) {
        output.writeSInt32NoTag(publisherCategories_.getInt(i));
      }
      if (bazCase_ == 5) {
        output.writeBool(
            5, (boolean)((java.lang.Boolean) baz_));
      }
      if (bazCase_ == 6) {
        output.writeInt32(
            6, (int)((java.lang.Integer) baz_));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (from_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getFrom());
      }
      if (lastUpdated_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getLastUpdated());
      }
      if (to_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getTo());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < publisherCategories_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeSInt32SizeNoTag(publisherCategories_.getInt(i));
        }
        size += dataSize;
        if (!getPublisherCategoriesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        publisherCategoriesMemoizedSerializedSize = dataSize;
      }
      if (bazCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(
              5, (boolean)((java.lang.Boolean) baz_));
      }
      if (bazCase_ == 6) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(
              6, (int)((java.lang.Integer) baz_));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof event.EventWrapper.GreetingWrapp)) {
        return super.equals(obj);
      }
      event.EventWrapper.GreetingWrapp other = (event.EventWrapper.GreetingWrapp) obj;

      if (hasFrom() != other.hasFrom()) return false;
      if (hasFrom()) {
        if (!getFrom()
            .equals(other.getFrom())) return false;
      }
      if (hasLastUpdated() != other.hasLastUpdated()) return false;
      if (hasLastUpdated()) {
        if (!getLastUpdated()
            .equals(other.getLastUpdated())) return false;
      }
      if (hasTo() != other.hasTo()) return false;
      if (hasTo()) {
        if (!getTo()
            .equals(other.getTo())) return false;
      }
      if (!getPublisherCategoriesList()
          .equals(other.getPublisherCategoriesList())) return false;
      if (!getBazCase().equals(other.getBazCase())) return false;
      switch (bazCase_) {
        case 5:
          if (getBazNull()
              != other.getBazNull()) return false;
          break;
        case 6:
          if (getBazValue()
              != other.getBazValue()) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFrom()) {
        hash = (37 * hash) + FROM_FIELD_NUMBER;
        hash = (53 * hash) + getFrom().hashCode();
      }
      if (hasLastUpdated()) {
        hash = (37 * hash) + LAST_UPDATED_FIELD_NUMBER;
        hash = (53 * hash) + getLastUpdated().hashCode();
      }
      if (hasTo()) {
        hash = (37 * hash) + TO_FIELD_NUMBER;
        hash = (53 * hash) + getTo().hashCode();
      }
      if (getPublisherCategoriesCount() > 0) {
        hash = (37 * hash) + PUBLISHER_CATEGORIES_FIELD_NUMBER;
        hash = (53 * hash) + getPublisherCategoriesList().hashCode();
      }
      switch (bazCase_) {
        case 5:
          hash = (37 * hash) + BAZ_NULL_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
              getBazNull());
          break;
        case 6:
          hash = (37 * hash) + BAZ_VALUE_FIELD_NUMBER;
          hash = (53 * hash) + getBazValue();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static event.EventWrapper.GreetingWrapp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static event.EventWrapper.GreetingWrapp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static event.EventWrapper.GreetingWrapp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static event.EventWrapper.GreetingWrapp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static event.EventWrapper.GreetingWrapp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static event.EventWrapper.GreetingWrapp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static event.EventWrapper.GreetingWrapp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static event.EventWrapper.GreetingWrapp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static event.EventWrapper.GreetingWrapp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static event.EventWrapper.GreetingWrapp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static event.EventWrapper.GreetingWrapp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static event.EventWrapper.GreetingWrapp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(event.EventWrapper.GreetingWrapp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code event.GreetingWrapp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:event.GreetingWrapp)
        event.EventWrapper.GreetingWrappOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return event.EventWrapper.internal_static_event_GreetingWrapp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return event.EventWrapper.internal_static_event_GreetingWrapp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                event.EventWrapper.GreetingWrapp.class, event.EventWrapper.GreetingWrapp.Builder.class);
      }

      // Construct using event.EventWrapper.GreetingWrapp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (fromBuilder_ == null) {
          from_ = null;
        } else {
          from_ = null;
          fromBuilder_ = null;
        }
        if (lastUpdatedBuilder_ == null) {
          lastUpdated_ = null;
        } else {
          lastUpdated_ = null;
          lastUpdatedBuilder_ = null;
        }
        if (toBuilder_ == null) {
          to_ = null;
        } else {
          to_ = null;
          toBuilder_ = null;
        }
        publisherCategories_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        bazCase_ = 0;
        baz_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return event.EventWrapper.internal_static_event_GreetingWrapp_descriptor;
      }

      @java.lang.Override
      public event.EventWrapper.GreetingWrapp getDefaultInstanceForType() {
        return event.EventWrapper.GreetingWrapp.getDefaultInstance();
      }

      @java.lang.Override
      public event.EventWrapper.GreetingWrapp build() {
        event.EventWrapper.GreetingWrapp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public event.EventWrapper.GreetingWrapp buildPartial() {
        event.EventWrapper.GreetingWrapp result = new event.EventWrapper.GreetingWrapp(this);
        int from_bitField0_ = bitField0_;
        if (fromBuilder_ == null) {
          result.from_ = from_;
        } else {
          result.from_ = fromBuilder_.build();
        }
        if (lastUpdatedBuilder_ == null) {
          result.lastUpdated_ = lastUpdated_;
        } else {
          result.lastUpdated_ = lastUpdatedBuilder_.build();
        }
        if (toBuilder_ == null) {
          result.to_ = to_;
        } else {
          result.to_ = toBuilder_.build();
        }
        if (((bitField0_ & 0x00000001) != 0)) {
          publisherCategories_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.publisherCategories_ = publisherCategories_;
        if (bazCase_ == 5) {
          result.baz_ = baz_;
        }
        if (bazCase_ == 6) {
          result.baz_ = baz_;
        }
        result.bazCase_ = bazCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof event.EventWrapper.GreetingWrapp) {
          return mergeFrom((event.EventWrapper.GreetingWrapp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(event.EventWrapper.GreetingWrapp other) {
        if (other == event.EventWrapper.GreetingWrapp.getDefaultInstance()) return this;
        if (other.hasFrom()) {
          mergeFrom(other.getFrom());
        }
        if (other.hasLastUpdated()) {
          mergeLastUpdated(other.getLastUpdated());
        }
        if (other.hasTo()) {
          mergeTo(other.getTo());
        }
        if (!other.publisherCategories_.isEmpty()) {
          if (publisherCategories_.isEmpty()) {
            publisherCategories_ = other.publisherCategories_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePublisherCategoriesIsMutable();
            publisherCategories_.addAll(other.publisherCategories_);
          }
          onChanged();
        }
        switch (other.getBazCase()) {
          case BAZ_NULL: {
            setBazNull(other.getBazNull());
            break;
          }
          case BAZ_VALUE: {
            setBazValue(other.getBazValue());
            break;
          }
          case BAZ_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        event.EventWrapper.GreetingWrapp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (event.EventWrapper.GreetingWrapp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bazCase_ = 0;
      private java.lang.Object baz_;
      public BazCase
          getBazCase() {
        return BazCase.forNumber(
            bazCase_);
      }

      public Builder clearBaz() {
        bazCase_ = 0;
        baz_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.StringValue from_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> fromBuilder_;
      /**
       * <code>.google.protobuf.StringValue from = 1;</code>
       * @return Whether the from field is set.
       */
      public boolean hasFrom() {
        return fromBuilder_ != null || from_ != null;
      }
      /**
       * <code>.google.protobuf.StringValue from = 1;</code>
       * @return The from.
       */
      public com.google.protobuf.StringValue getFrom() {
        if (fromBuilder_ == null) {
          return from_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : from_;
        } else {
          return fromBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.StringValue from = 1;</code>
       */
      public Builder setFrom(com.google.protobuf.StringValue value) {
        if (fromBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          from_ = value;
          onChanged();
        } else {
          fromBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue from = 1;</code>
       */
      public Builder setFrom(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (fromBuilder_ == null) {
          from_ = builderForValue.build();
          onChanged();
        } else {
          fromBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue from = 1;</code>
       */
      public Builder mergeFrom(com.google.protobuf.StringValue value) {
        if (fromBuilder_ == null) {
          if (from_ != null) {
            from_ =
              com.google.protobuf.StringValue.newBuilder(from_).mergeFrom(value).buildPartial();
          } else {
            from_ = value;
          }
          onChanged();
        } else {
          fromBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue from = 1;</code>
       */
      public Builder clearFrom() {
        if (fromBuilder_ == null) {
          from_ = null;
          onChanged();
        } else {
          from_ = null;
          fromBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue from = 1;</code>
       */
      public com.google.protobuf.StringValue.Builder getFromBuilder() {
        
        onChanged();
        return getFromFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.StringValue from = 1;</code>
       */
      public com.google.protobuf.StringValueOrBuilder getFromOrBuilder() {
        if (fromBuilder_ != null) {
          return fromBuilder_.getMessageOrBuilder();
        } else {
          return from_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : from_;
        }
      }
      /**
       * <code>.google.protobuf.StringValue from = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getFromFieldBuilder() {
        if (fromBuilder_ == null) {
          fromBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getFrom(),
                  getParentForChildren(),
                  isClean());
          from_ = null;
        }
        return fromBuilder_;
      }

      private com.google.protobuf.Timestamp lastUpdated_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> lastUpdatedBuilder_;
      /**
       * <code>.google.protobuf.Timestamp last_updated = 2;</code>
       * @return Whether the lastUpdated field is set.
       */
      public boolean hasLastUpdated() {
        return lastUpdatedBuilder_ != null || lastUpdated_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp last_updated = 2;</code>
       * @return The lastUpdated.
       */
      public com.google.protobuf.Timestamp getLastUpdated() {
        if (lastUpdatedBuilder_ == null) {
          return lastUpdated_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdated_;
        } else {
          return lastUpdatedBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp last_updated = 2;</code>
       */
      public Builder setLastUpdated(com.google.protobuf.Timestamp value) {
        if (lastUpdatedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          lastUpdated_ = value;
          onChanged();
        } else {
          lastUpdatedBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp last_updated = 2;</code>
       */
      public Builder setLastUpdated(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (lastUpdatedBuilder_ == null) {
          lastUpdated_ = builderForValue.build();
          onChanged();
        } else {
          lastUpdatedBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp last_updated = 2;</code>
       */
      public Builder mergeLastUpdated(com.google.protobuf.Timestamp value) {
        if (lastUpdatedBuilder_ == null) {
          if (lastUpdated_ != null) {
            lastUpdated_ =
              com.google.protobuf.Timestamp.newBuilder(lastUpdated_).mergeFrom(value).buildPartial();
          } else {
            lastUpdated_ = value;
          }
          onChanged();
        } else {
          lastUpdatedBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp last_updated = 2;</code>
       */
      public Builder clearLastUpdated() {
        if (lastUpdatedBuilder_ == null) {
          lastUpdated_ = null;
          onChanged();
        } else {
          lastUpdated_ = null;
          lastUpdatedBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp last_updated = 2;</code>
       */
      public com.google.protobuf.Timestamp.Builder getLastUpdatedBuilder() {
        
        onChanged();
        return getLastUpdatedFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp last_updated = 2;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getLastUpdatedOrBuilder() {
        if (lastUpdatedBuilder_ != null) {
          return lastUpdatedBuilder_.getMessageOrBuilder();
        } else {
          return lastUpdated_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdated_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp last_updated = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getLastUpdatedFieldBuilder() {
        if (lastUpdatedBuilder_ == null) {
          lastUpdatedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getLastUpdated(),
                  getParentForChildren(),
                  isClean());
          lastUpdated_ = null;
        }
        return lastUpdatedBuilder_;
      }

      private com.google.protobuf.StringValue to_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> toBuilder_;
      /**
       * <code>.google.protobuf.StringValue to = 3;</code>
       * @return Whether the to field is set.
       */
      public boolean hasTo() {
        return toBuilder_ != null || to_ != null;
      }
      /**
       * <code>.google.protobuf.StringValue to = 3;</code>
       * @return The to.
       */
      public com.google.protobuf.StringValue getTo() {
        if (toBuilder_ == null) {
          return to_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : to_;
        } else {
          return toBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.StringValue to = 3;</code>
       */
      public Builder setTo(com.google.protobuf.StringValue value) {
        if (toBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          to_ = value;
          onChanged();
        } else {
          toBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue to = 3;</code>
       */
      public Builder setTo(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (toBuilder_ == null) {
          to_ = builderForValue.build();
          onChanged();
        } else {
          toBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue to = 3;</code>
       */
      public Builder mergeTo(com.google.protobuf.StringValue value) {
        if (toBuilder_ == null) {
          if (to_ != null) {
            to_ =
              com.google.protobuf.StringValue.newBuilder(to_).mergeFrom(value).buildPartial();
          } else {
            to_ = value;
          }
          onChanged();
        } else {
          toBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue to = 3;</code>
       */
      public Builder clearTo() {
        if (toBuilder_ == null) {
          to_ = null;
          onChanged();
        } else {
          to_ = null;
          toBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue to = 3;</code>
       */
      public com.google.protobuf.StringValue.Builder getToBuilder() {
        
        onChanged();
        return getToFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.StringValue to = 3;</code>
       */
      public com.google.protobuf.StringValueOrBuilder getToOrBuilder() {
        if (toBuilder_ != null) {
          return toBuilder_.getMessageOrBuilder();
        } else {
          return to_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : to_;
        }
      }
      /**
       * <code>.google.protobuf.StringValue to = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getToFieldBuilder() {
        if (toBuilder_ == null) {
          toBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getTo(),
                  getParentForChildren(),
                  isClean());
          to_ = null;
        }
        return toBuilder_;
      }

      private com.google.protobuf.Internal.IntList publisherCategories_ = emptyIntList();
      private void ensurePublisherCategoriesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          publisherCategories_ = mutableCopy(publisherCategories_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated sint32 publisher_categories = 4;</code>
       * @return A list containing the publisherCategories.
       */
      public java.util.List<java.lang.Integer>
          getPublisherCategoriesList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(publisherCategories_) : publisherCategories_;
      }
      /**
       * <code>repeated sint32 publisher_categories = 4;</code>
       * @return The count of publisherCategories.
       */
      public int getPublisherCategoriesCount() {
        return publisherCategories_.size();
      }
      /**
       * <code>repeated sint32 publisher_categories = 4;</code>
       * @param index The index of the element to return.
       * @return The publisherCategories at the given index.
       */
      public int getPublisherCategories(int index) {
        return publisherCategories_.getInt(index);
      }
      /**
       * <code>repeated sint32 publisher_categories = 4;</code>
       * @param index The index to set the value at.
       * @param value The publisherCategories to set.
       * @return This builder for chaining.
       */
      public Builder setPublisherCategories(
          int index, int value) {
        ensurePublisherCategoriesIsMutable();
        publisherCategories_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sint32 publisher_categories = 4;</code>
       * @param value The publisherCategories to add.
       * @return This builder for chaining.
       */
      public Builder addPublisherCategories(int value) {
        ensurePublisherCategoriesIsMutable();
        publisherCategories_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sint32 publisher_categories = 4;</code>
       * @param values The publisherCategories to add.
       * @return This builder for chaining.
       */
      public Builder addAllPublisherCategories(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensurePublisherCategoriesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, publisherCategories_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sint32 publisher_categories = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPublisherCategories() {
        publisherCategories_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      /**
       * <pre>
       * always set this to "true" when null
       * </pre>
       *
       * <code>bool baz_null = 5;</code>
       * @return Whether the bazNull field is set.
       */
      public boolean hasBazNull() {
        return bazCase_ == 5;
      }
      /**
       * <pre>
       * always set this to "true" when null
       * </pre>
       *
       * <code>bool baz_null = 5;</code>
       * @return The bazNull.
       */
      public boolean getBazNull() {
        if (bazCase_ == 5) {
          return (java.lang.Boolean) baz_;
        }
        return false;
      }
      /**
       * <pre>
       * always set this to "true" when null
       * </pre>
       *
       * <code>bool baz_null = 5;</code>
       * @param value The bazNull to set.
       * @return This builder for chaining.
       */
      public Builder setBazNull(boolean value) {
        bazCase_ = 5;
        baz_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * always set this to "true" when null
       * </pre>
       *
       * <code>bool baz_null = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearBazNull() {
        if (bazCase_ == 5) {
          bazCase_ = 0;
          baz_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>int32 baz_value = 6;</code>
       * @return Whether the bazValue field is set.
       */
      public boolean hasBazValue() {
        return bazCase_ == 6;
      }
      /**
       * <code>int32 baz_value = 6;</code>
       * @return The bazValue.
       */
      public int getBazValue() {
        if (bazCase_ == 6) {
          return (java.lang.Integer) baz_;
        }
        return 0;
      }
      /**
       * <code>int32 baz_value = 6;</code>
       * @param value The bazValue to set.
       * @return This builder for chaining.
       */
      public Builder setBazValue(int value) {
        bazCase_ = 6;
        baz_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 baz_value = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearBazValue() {
        if (bazCase_ == 6) {
          bazCase_ = 0;
          baz_ = null;
          onChanged();
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:event.GreetingWrapp)
    }

    // @@protoc_insertion_point(class_scope:event.GreetingWrapp)
    private static final event.EventWrapper.GreetingWrapp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new event.EventWrapper.GreetingWrapp();
    }

    public static event.EventWrapper.GreetingWrapp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GreetingWrapp>
        PARSER = new com.google.protobuf.AbstractParser<GreetingWrapp>() {
      @java.lang.Override
      public GreetingWrapp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GreetingWrapp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GreetingWrapp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GreetingWrapp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public event.EventWrapper.GreetingWrapp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_event_GreetingWrapp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_event_GreetingWrapp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023event_wrapper.proto\022\005event\032\037google/pro" +
      "tobuf/timestamp.proto\032\014tagger.proto\032\036goo" +
      "gle/protobuf/wrappers.proto\"\345\001\n\rGreeting" +
      "Wrapp\022*\n\004from\030\001 \001(\0132\034.google.protobuf.St" +
      "ringValue\0220\n\014last_updated\030\002 \001(\0132\032.google" +
      ".protobuf.Timestamp\022(\n\002to\030\003 \001(\0132\034.google" +
      ".protobuf.StringValue\022\034\n\024publisher_categ" +
      "ories\030\004 \003(\021\022\022\n\010baz_null\030\005 \001(\010H\000\022\023\n\tbaz_v" +
      "alue\030\006 \001(\005H\000B\005\n\003bazB.Z,github.com/davida" +
      "e/proto-definition/proto/gob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          tagger.Tagger.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_event_GreetingWrapp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_event_GreetingWrapp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_event_GreetingWrapp_descriptor,
        new java.lang.String[] { "From", "LastUpdated", "To", "PublisherCategories", "BazNull", "BazValue", "Baz", });
    com.google.protobuf.TimestampProto.getDescriptor();
    tagger.Tagger.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
